### ISSUE TITLE
Request to be added to TextLint (and Text Editors)

### ISSUE THREAD

**Issue by BrandonKMLee** [defmethodinc/just-not-sorry#116]
As observed by https://github.com/textlint/textlint/issues/750 it would be useful if TextLint has this feature.

Assisting documentation: https://textlint.github.io/docs/rule.html

Reasoning to have this: The software could be applied to MarkText or Zettlr, or some other text editor.

**Comment by sbrudz** [comment]
This is a good idea, but outside the scope of the project.  We're just focused on browser extensions.  You're welcome to use JustNotSorry's logic/content to create your own repo for the TextLint version.  If you create one, we'd be happy to put a link on JustNotSorry's ReadMe to help others find it.
