### ISSUE TITLE
Error on outlook.office.com

### ISSUE THREAD

**Issue by sbrudz** [defmethodinc/just-not-sorry#141]
While testing on outlook.office.com, Tami got the following error:
![image](https://user-images.githubusercontent.com/1520763/148942016-ea766062-bca3-46e0-997a-b9cc489cf905.png)

> It seems that it happened once I opened an email not in the main pane but in the modal that shows up if theres an attachment that you are previewing.  But when I did the same thing (opened another email with a different attachment), nothing happened.

The first attachment was an excel document.

This is the last known issue blocking full public release of v2.1.

**Comment by tamireiss** [comment]
To be clear, I think we can release if this isn’t resolved easily and quickly. The user doesn’t experience anything and I only noticed the errors because I’m in developer mode on the extensions page.

-Tami
@tamireiss / tamireiss.com ( http://tamireiss.com )

Sent via Superhuman iOS ( ***@***.*** )

**Comment by sbrudz** [comment]
@tamireiss That's good to know.  The fix was easy, so hopefully the release above resolves the issue and we can release.
