### ISSUE TITLE
Add two more expressions as warnings

### ISSUE THREAD

**Issue by sbrudz** [defmethodinc/just-not-sorry#144]
Request from MSc Patricia Koops via the just-not-sorry email list:
> Hi,
> 
> I hope this email find you well.
> 
> I miss two expressions in your app which women use a lot and should not use:
> 
> “If that’s okay”
> 
> and
> 
> “if that makes sense.”
> 
> Please add it.
> 
> Thanks!
> 
> BW,
> 
> LG,
> 
> Met vriendelijke groeten,
> 
> MSc Patricia Koops
> 
> Transformational Life Coach
> 
> Follow me on Instagram: https://www.instagram.com/fiercely_kind_coaching/

**Comment by sbrudz** [comment]
PR #151 completes half of this request.  For the other half, I need to sync up with @tamireiss about what text and source to use for "If that’s okay".  The original source provided by Patricia was [this tweet](https://twitter.com/LShalott/status/1477082150960832519?t=QgGs6DdDjBtxVkPiFfSiRg&s=19).  There's not much context as to why someone shouldn't use this phrase, though.

**Comment by tamireiss** [comment]
Let’s use the same copy from “does that make sense

-Tami
@tamireiss / tamireiss.com ( http://tamireiss.com )

Sent via Superhuman iOS ( ***@***.*** )
