### ISSUE TITLE
Highlights are sometimes mis-located 

### ISSUE THREAD

**Issue by ProfJanetDavis** [defmethodinc/just-not-sorry#54]
This is on Chrome Version 74.0.3729.169 (Official Build) (64-bit MacOS). Note the two highlights are for the warnings "should" and "I think" far above.

![Screen Shot 2019-06-19 at 9 54 24 AM](https://user-images.githubusercontent.com/19829843/59804220-84b01400-92a2-11e9-911a-765f45fc035a.png)

**Comment by janetlndavis** [comment]
I ran the tests supplied in SpecRunner.html and saw the following test failures:

![Screen Shot 2019-06-19 at 2 59 46 PM](https://user-images.githubusercontent.com/19829843/59804387-0607a680-92a3-11e9-850a-5f525f1fea28.png)
![Screen Shot 2019-06-19 at 3 00 09 PM](https://user-images.githubusercontent.com/19829843/59804386-0607a680-92a3-11e9-94e9-09a38778db95.png)
![Screen Shot 2019-06-19 at 3 00 28 PM](https://user-images.githubusercontent.com/19829843/59804385-0607a680-92a3-11e9-8213-7731c601f043.png)

**Comment by sbrudz** [comment]
The highlight mis-location issue appears to only happen for forwarded emails.  New email compose and reply seem to position correctly.

**Comment by ProfJanetDavis** [comment]
Hi Steve, thanks for looking into this! I found the problem still occurs in a reply if the email is long enough. I'm using Chrome 79.0.3945.88 on Mac OS 10.14.6. 

Here's a screenshot:
![Screen Shot 2020-01-02 at 9 26 52 AM](https://user-images.githubusercontent.com/19829843/71681689-2e885700-2d42-11ea-8d75-4ffdf8031282.png)

**Comment by ProfJanetDavis** [comment]
Here's a screenshot from a long reply. You can see the underlines appear quite a distance below where the word "just" appears in the text. At this point, they are pretty unusable.

![Screen Shot 2020-01-02 at 11 07 45 AM](https://user-images.githubusercontent.com/19829843/71686511-39e27f00-2d50-11ea-8360-3a7b24d1e535.png)

Here's a constructed example to make the problem a bit easier to see:
![Screen Shot 2020-01-02 at 9 26 52 AM](https://user-images.githubusercontent.com/19829843/71686567-63030f80-2d50-11ea-877d-cd8100daf34c.png)
