### ISSUE TITLE
Document Phrases The Algo Looks For In README?

### ISSUE THREAD

**Issue by JimLynchCodes** [defmethodinc/just-not-sorry#57]
The links to articles are a great addition to this README that I don't think were there last time I looked at this repo!

I think it would be awesome if the README spelled out which phrases it highlights. For example, I wanted to suggest adding "I'll try" to the list but wasn't sure if that was already in the list. Also, for general users it would be nice to see what all the supported phrases are so they can easily and quickly give feedback or suggest new things! ❤️

**Comment by ProfJanetDavis** [comment]
I support this suggestion. I had to read the source code to find this information, and that's not accessible to everyone.

**Comment by maniacialexa** [comment]
Read all the phrases that are listed, which is then an output to the readme. I would prefer the automatic approach where the readme is instantly updated.

**Comment by sbrudz** [comment]
Warning phrases are now listed on the justnotsorry.com web site: https://justnotsorry.com/phrases.html

They're also listed on the extension options UI (via chrome://extensions or just click the JustNotSorry logo in the extension section of the Chrome toolbar).

**Comment by tamireiss** [comment]
Cool

-Tami
@tamireiss / tamireiss.com ( http://tamireiss.com )

Sent via Superhuman iOS ( ***@***.*** )
