### ISSUE TITLE
Slow typing performance on long emails

### ISSUE THREAD

**Issue by sbrudz** [defmethodinc/just-not-sorry#65]
While testing the last few pull requests, I've noticed that typing into long emails is very laggy.  I profiled the code and found that the checkForWarnings function in just-not-sorry is the culprit.  It adds and removes the warnings each time you type a character.  This causes Chrome to recalculate the layout of the DOM over and over again, which is slow when there are a lot of nodes being impacted.  We should implement a less expensive method of handling warnings to address this issue.  The changes needed to fix this issue could also serve as a base for being able to implement #59 .
![just-not-sorry-profile](https://user-images.githubusercontent.com/1520763/74113121-d6761900-4b67-11ea-8035-8c00d4023744.png)

**Comment by maniacialexa** [comment]
In progress - 2 days thus far writing tests because we were missing test coverage. About another day of work.
