### ISSUE TITLE
Automate incrementing of version number

### ISSUE THREAD

**Issue by sbrudz** [defmethodinc/just-not-sorry#71]
One of the challenges of the manual release process is that the version number needs to be incremented manually and release notes need to be generated for the change set.  To automate this, use the [semantic-release](https://semantic-release.gitbook.io/semantic-release/) package.  

To enable a round of testing before releasing changes to the broader public, we should also set up a [pre-release branch](https://github.com/semantic-release/semantic-release/blob/0785a844fa8ac1320383452ce531898be3b01f92/docs/recipes/pre-releases.md).

Finally, set up a [linter](https://github.com/conventional-changelog/commitlint) and use [husky](https://github.com/typicode/husky) to ensure that commit messages use the correct format.

**Comment by maniacialexa** [comment]
This ticket is in progress.
