### ISSUE TITLE
Seems to break sending emails

### ISSUE THREAD

**Issue by nbali** [defmethodinc/just-not-sorry#73]
Chrome: Verzió: 81.0.4044.92 (Hivatalos verzió) (64 bites), No other extensions, Default theme, Tested with 2 profiles
Just Not Sorry -- the Gmail Plug-in: Verzió 1.6.1
Windows 10 Pro: Verziószám	10.0.18362 build 18362

I can open the compose dialog, fill out everything, press send, and then nothing happens. Nothing in the console either.

**Comment by sbrudz** [comment]
Thank you for reporting this issue and providing exact versions.  I just tested using the same version of Windows, Chrome, and Just Not Sorry, but didn't hit an issue.  Perhaps there's another difference between our environments that's causing an issue.  A few questions to help narrow things down:

* What language and region is your Windows 10 configured to use?
* If you compose a new email with "To" and "Subject" filled out but an empty body, does that change the behavior at all?
* If you disable the extension, can you send emails normally?

**Comment by nbali** [comment]
- Hungarian, Hungary, etc (Not sure how it's exactly called, but doubt there is more.)
- I actually tested it with empty body before, because I had to repeat so many times. Anyway seems no different with or without a body.
- Yes. GMail loaded with extension enabled can't send the mail, GMail loaded without can.

**Comment by sbrudz** [comment]
I was able to reproduce the issue by switching the display language for my Gmail to Magyar.  I'm now trying to track down the root cause.  I tried some other display languages and had mixed results -- French works fine but Turkish fails to send with a different error.  I'll keep you posted.

**Comment by sbrudz** [comment]
I found the root cause of the issue.  I'll work on a fix for it tomorrow.  Thanks for reporting this!

**Comment by jajosolo** [comment]
The chrome webstore still has version 1.6.1 (the one that breaks gmail). I see you fixed and published version 7.0 on GitHub.

Can you update on Chrome Webstore as well?

Also, you may want to check up the extension support forum on Chrome Webstore and maybe even respond here: https://chrome.google.com/webstore/detail/just-not-sorry-the-gmail/fmegmibednnlgojepmidhlhpjbppmlci
(go to "support")

thanks

**Comment by sbrudz** [comment]
Thank you for the heads up @jajosolo.  The fix for this has been submitted to the Chrome Webstore as version 1.6.2. It's in the Pending Review status at the moment. Hopefully, it will be reviewed and accepted soon by the curators.  I'll update this issue when it's been released to the public and will also update the extension support section.

**Comment by sbrudz** [comment]
Version 1.6.2 has been approved and is now available.  Hopefully, this resolves the problem you're seeing.  If you still find that the extension is breaking Gmail, please let us know.  Thank you!
